version: '3'
services:
  api:
    image: 'com.pillar/artisan-bootcamp-project'
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
    depends_on:
      - "mysql"
  mysql:
    image: 'mysql:8.0.13'
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'cc_processing'
